# Dockerfile para Load Balancer
FROM nginx:1.27-alpine

# Copiar configuração do load balancer
COPY nginx-loadbalancer.conf /etc/nginx/conf.d/default.conf

# Remover configuração default do nginx
RUN rm -f /etc/nginx/conf.d/default.conf.default

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
