FROM node:20-alpine

WORKDIR /app


COPY package*.json ./
COPY dayjs-1.11.10.tgz ./


RUN npm install


COPY . .


EXPOSE 5173

# Comando para desenvolvimento com hot reload
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]